#!/usr/bin/env python3
"""Emit sealed REAL_SOURCE_BACKED packet specimen-054 (CPython opcode metadata regen drift)."""
from __future__ import annotations

from emit_specimen import emit
from compile_seed import write_seed
from paths import SPECIMENS
from update_index import main as update_index


packet = dict(
    id="specimen-054",
    manifest="""
id: specimen-054
kind: REAL_SOURCE_BACKED
repository: python/cpython
failing_ref: de70614c1387636c8f835ee3e4eb36c8ae721f21
fixed_ref: 3fa30d9e9c13c4b84bdc9fc04e33130775679e98
source_issue: https://github.com/python/cpython/issues/134236
source_pr: https://github.com/python/cpython/pull/134231
mechanism_tags:
  - generated-code-drift
  - stale-generated-header
  - regen-all
ecosystem: c
reproduction_status: source-backed
safety_status: not-executed-on-host
packet_tokens_estimate: 7000
answer_key_sealed: true
parent_specimens: []
mutations: []
""",
    task="""# TASK

GitHub Actions job `Tests / Check if generated files are up to date` (`check-generated-files`) fails on main after a generator change landed.

The job log for run 15115778970 includes a diff of `Include/internal/pycore_opcode_metadata.h` inside `_PyOpcode_Deopt`:

```
-    [119] = 119,
-    [120] = 120,
     [121] = 121,
...
-    [211] = 211,
     [212] = 212,
```

The same revision already contains a `// This file is generated by Tools/cases_generator/opcode_metadata_generator.py` header, and `Tools/cases_generator/opcode_metadata_generator.py` was just changed to emit identity rows for opcode numbers missing from `analysis.opmap`.

The developer wants to know which checked-in generated file disagrees with `make regen-all`, and how those numeric identity rows relate to named opcode ids on the same revision.
""",
    observed="""# OBSERVED

Public python/cpython issue 134236 / PR 134231. Failing world after merge of #128044 (`cc9add695da42defc72e62c5d5389621dac54b2b`, "Mark unknown opcodes as deopting to themselves").

CI job name: `Check if generated files are up to date`.
CI log (issue 134236, actions run 15115778970):

```
Generated files not up to date.
Perhaps you forgot to run make regen-all or build.bat --regen. ;)
```

plus the `_PyOpcode_Deopt` hunk above.

On the failing revision, `generate_deopt_table` in `opcode_metadata_generator.py` does:

1. one named row per `analysis.instructions` (`[inst.name] = deopt`)
2. then, for every `i in range(256)` whose value is **not** in `analysis.opmap.values()`, a numeric row `[i] = i`
3. `assert len(deopts) == 256`

Checked-in `Include/internal/pycore_opcode_metadata.h` on that revision starts `_PyOpcode_Deopt` with numeric keys including 119, 120, and 211.

`Include/opcode_ids.h` on the same revision:

```
#define UNPACK_SEQUENCE                        119
#define YIELD_VALUE                            120
#define UNPACK_SEQUENCE_TWO_TUPLE              211
```

The same generated header also already has named deopt rows later in the table:

```
[UNPACK_SEQUENCE] = UNPACK_SEQUENCE,
[UNPACK_SEQUENCE_TWO_TUPLE] = UNPACK_SEQUENCE,
[YIELD_VALUE] = YIELD_VALUE,
```

`Makefile.pre.in` `regen-opcode-metadata` runs `opcode_metadata_generator.py` against `Python/bytecodes.c` and updates `pycore_opcode_metadata.h`. `regen-all` includes `regen-cases`, which includes `regen-opcode-metadata`.

This packet does not include a local clone; treat the snippets and CI message as the world. Do not execute untrusted checkouts on the host.
""",
    commands="""# COMMANDS

```
# CI job: check-generated-files
#   name: Check if generated files are up to date
./configure --config-cache --with-pydebug --enable-shared
make -j4 regen-all
make regen-stdlib-module-names regen-sbom regen-unicodedata
git add -u
git status --porcelain
git diff -- Include/internal/pycore_opcode_metadata.h
```

Not executed on this lab host.
""",
    tree="""python/cpython
  Include/internal/pycore_opcode_metadata.h
  Include/opcode_ids.h
  Python/bytecodes.c
  Tools/cases_generator/opcode_metadata_generator.py
  Makefile.pre.in
  .github/workflows/build.yml
""",
    source="""repository: python/cpython
issue: https://github.com/python/cpython/issues/134236
pr: https://github.com/python/cpython/pull/134231
triggering_pr: https://github.com/python/cpython/pull/128044
triggering_commit: cc9add695da42defc72e62c5d5389621dac54b2b
failing_ref (merge first parent of #134231): de70614c1387636c8f835ee3e4eb36c8ae721f21
fixed_ref (merge commit of #134231): 3fa30d9e9c13c4b84bdc9fc04e33130775679e98
head_sha: 63c39b3dc5f81d1c3a6d4ff9d4596578a03cf382
merged_at: 2025-05-19
merged_by: DinoV
changed_files: Include/internal/pycore_opcode_metadata.h
ci_job: https://github.com/python/cpython/actions/runs/15115778970/job/42485985691
""",
    answer_key="""KNOWN FIX (sealed): python/cpython PR 134231 merge 3fa30d9e9c13c4b84bdc9fc04e33130775679e98.

#128044 updated opcode_metadata_generator.py so unused bytecode numbers identity-deopt to themselves, and also edited the checked-in pycore_opcode_metadata.h. The header patch added numeric rows [119]=119, [120]=120, and [211]=211. Those numbers are already UNPACK_SEQUENCE, YIELD_VALUE, and UNPACK_SEQUENCE_TWO_TUPLE in opcode_ids.h / analysis.opmap, so a real regen-opcode-metadata pass never emits those three numeric keys (named rows already occupy those slots). CI check-generated-files runs make regen-all and sees exactly that three-line deletion.

Repair: commit the regen-all output for Include/internal/pycore_opcode_metadata.h (drop the three colliding identity rows). No generator logic change.

Do not show this to Dreamers, initial Red Pen, initial Grounders, or first-selection judges.
""",
    curation="""ACCEPT_R1

contrastiveness: high (numeric identity keys 119/120/211 vs named UNPACK_SEQUENCE/YIELD_VALUE/UNPACK_SEQUENCE_TWO_TUPLE on the same revision; generator uses opmap membership)
reproducibility: source-backed issue + PR + pinned merge parent/merge commit; local run not claimed
information density: high
safety: public OSS, not executed on host
nontriviality: high — generator and generated header landed together, yet the header was not the generator's output because hand-added numeric slots collided with already-mapped opcodes
ecosystem: c / cpython
mechanism_family: generated-code-drift, stale-generated-header, regen-all

Packet is the failing world only. Do not assume a root cause.
""",
    files={
        "generate_deopt_table.py": '''# Reduced excerpt of generate_deopt_table on failing_ref
# Tools/cases_generator/opcode_metadata_generator.py

def generate_deopt_table(analysis: Analysis, out: CWriter) -> None:
    out.emit("extern const uint8_t _PyOpcode_Deopt[256];\\n")
    out.emit("#ifdef NEED_OPCODE_METADATA\\n")
    out.emit("const uint8_t _PyOpcode_Deopt[256] = {\\n")
    deopts: list[tuple[str, str]] = []
    for inst in analysis.instructions.values():
        deopt = inst.name
        if inst.family is not None:
            deopt = inst.family.name
        deopts.append((inst.name, deopt))
    defined = set(analysis.opmap.values())
    for i in range(256):
        if i not in defined:
            deopts.append((f'{i}', f'{i}'))

    assert len(deopts) == 256
    assert len(set(x[0] for x in deopts)) == 256
    for name, deopt in sorted(deopts):
        out.emit(f"[{name}] = {deopt},\\n")
    out.emit("};\\n\\n")
''',
        "deopt_table_failing.h": '''// This file is generated by Tools/cases_generator/opcode_metadata_generator.py
// from:
//   Python/bytecodes.c
// Do not edit!
//
// Reduced excerpt of _PyOpcode_Deopt on failing_ref
// Include/internal/pycore_opcode_metadata.h

const uint8_t _PyOpcode_Deopt[256] = {
    [119] = 119,
    [120] = 120,
    [121] = 121,
    [122] = 122,
    [123] = 123,
    [124] = 124,
    [125] = 125,
    [126] = 126,
    [127] = 127,
    [211] = 211,
    [212] = 212,
    [213] = 213,
    /* ... named rows later in the same table ... */
    [UNPACK_SEQUENCE] = UNPACK_SEQUENCE,
    [UNPACK_SEQUENCE_LIST] = UNPACK_SEQUENCE,
    [UNPACK_SEQUENCE_TUPLE] = UNPACK_SEQUENCE,
    [UNPACK_SEQUENCE_TWO_TUPLE] = UNPACK_SEQUENCE,
    [YIELD_VALUE] = YIELD_VALUE,
};
''',
        "opcode_ids.excerpt.h": '''/* Include/opcode_ids.h on failing_ref (generated; numbers only). */
#define UNPACK_SEQUENCE                        119
#define YIELD_VALUE                            120
#define UNPACK_SEQUENCE_LIST                   209
#define UNPACK_SEQUENCE_TUPLE                  210
#define UNPACK_SEQUENCE_TWO_TUPLE              211
''',
        "ci_check.excerpt.yml": '''# .github/workflows/build.yml on failing_ref (reduced)

check-generated-files:
  name: 'Check if generated files are up to date'
  runs-on: ubuntu-24.04
  steps:
    - name: Build CPython
      run: |
        make -j4 regen-all
        make regen-stdlib-module-names regen-sbom regen-unicodedata
    - name: Check for changes
      run: |
        git add -u
        changes=$(git status --porcelain)
        if test -n "$changes"; then
          echo "Generated files not up to date."
          echo "Perhaps you forgot to run make regen-all or build.bat --regen. ;)"
          echo "$changes"
          git diff --staged || true
          exit 1
        fi
''',
    },
)

if __name__ == "__main__":
    dest = emit(packet)
    seed = write_seed(SPECIMENS / "specimen-054")
    print(dest)
    print(seed)
    update_index()
