// This file is generated by Tools/cases_generator/opcode_metadata_generator.py
// from:
//   Python/bytecodes.c
// Do not edit!
//
// Reduced excerpt of _PyOpcode_Deopt on failing_ref
// Include/internal/pycore_opcode_metadata.h

const uint8_t _PyOpcode_Deopt[256] = {
    [119] = 119,
    [120] = 120,
    [121] = 121,
    [122] = 122,
    [123] = 123,
    [124] = 124,
    [125] = 125,
    [126] = 126,
    [127] = 127,
    [211] = 211,
    [212] = 212,
    [213] = 213,
    /* ... named rows later in the same table ... */
    [UNPACK_SEQUENCE] = UNPACK_SEQUENCE,
    [UNPACK_SEQUENCE_LIST] = UNPACK_SEQUENCE,
    [UNPACK_SEQUENCE_TUPLE] = UNPACK_SEQUENCE,
    [UNPACK_SEQUENCE_TWO_TUPLE] = UNPACK_SEQUENCE,
    [YIELD_VALUE] = YIELD_VALUE,
};
